-- Seed data generated from technologies-content-with-outcomes.json

-- Insert categories
INSERT INTO technology_category (id, name) VALUES (1, 'Architecture & Design');
INSERT INTO technology_category (id, name) VALUES (2, 'Frontend Development');
INSERT INTO technology_category (id, name) VALUES (3, 'Backend Development');
INSERT INTO technology_category (id, name) VALUES (4, 'Database & Performance');
INSERT INTO technology_category (id, name) VALUES (5, 'Cloud & DevOps');
INSERT INTO technology_category (id, name) VALUES (6, 'Modern Development Practices');
INSERT INTO technology_category (id, name) VALUES (7, 'Technical Research & Prototyping');
INSERT INTO technology_category (id, name) VALUES (8, 'Edge Architectures (Production)');
INSERT INTO technology_category (id, name) VALUES (9, 'Legacy Development');

-- Insert technologies

-- Architecture & Design
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (1, 'full-stack-service-decomposition-1', 'Full-Stack Service Decomposition', '5+ years (CCHQ)', 5, 85, 'Advanced', 'Decomposed monolithic applications into independent full-stack services at CCHQ, enabling team autonomy and faster deployment cycles.', 'Architecture & Design', NULL, 1, 'Broke down monolithic applications into modular, independently deployable services', 'Enabled teams to deploy independently and faster', 'Cut release cycles from weeks to days', 'CCHQ national campaign platform');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (2, 'service-oriented-architecture-1', 'Service-Oriented Architecture', '8+ years', 8, 88, 'Advanced', 'Designed and implemented service-oriented architectures across enterprise systems for 8+ years, improving modularity and integration flexibility.', 'Architecture & Design', NULL, 1, 'Designed and implemented SOA patterns across 10+ enterprise applications', 'Improved system modularity and enabled seamless third-party integrations', 'Reduced integration time by 60% and increased system maintainability', 'CCHQ national campaign platform');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (3, 'restful-apis-1', 'RESTful APIs', '10+ years', 10, 90, 'Expert', 'Built and maintained RESTful APIs for 10+ years, delivering scalable and well-documented interfaces for client-server communication.', 'Architecture & Design', NULL, 1, 'Architected and maintained 50+ RESTful APIs with comprehensive OpenAPI documentation', 'Enabled rapid client integration and self-service API adoption', 'Reduced integration support tickets by 80% and enabled 100+ external integrations', 'CCHQ national campaign platform');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (4, 'component-based-architecture-1', 'Component-Based Architecture', '3+ years', 3, 85, 'Advanced', 'Developed reusable component-based architectures for 3+ years, improving code maintainability and development velocity.', 'Architecture & Design', NULL, 1, 'Developed reusable component libraries with strict encapsulation and interfaces', 'Improved code maintainability and accelerated development velocity', 'Reduced new feature development time by 40%', 'CCHQ national campaign platform');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (5, 'independent-deployment-1', 'Independent Deployment', '5+ years', 5, 85, 'Advanced', 'Enabled independent deployment pipelines for services over 5+ years, reducing release coordination overhead and deployment risk.', 'Architecture & Design', NULL, 1, 'Implemented independent deployment pipelines with automated testing and rollback', 'Reduced release coordination overhead and deployment risk', 'Enabled daily deployments vs. monthly releases', 'CCHQ national campaign platform');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (6, 'message-queue-patterns-1', 'Message Queue Patterns', '8+ years (MSMQ, SQL-based)', 8, 85, 'Advanced', 'Implemented message queue patterns using MSMQ and SQL-based queues for 8+ years, ensuring reliable asynchronous processing.', 'Architecture & Design', NULL, 1, 'Implemented reliable message queuing with MSMQ and SQL-based queues', 'Ensured fault-tolerant asynchronous processing at scale', 'Achieved 99.9% message delivery with automatic retry and dead-letter handling', 'CCHQ national campaign platform');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (7, 'edge-architectures-1', 'Edge Architectures', '1+ years', 1, 80, 'Advanced', 'Architected edge computing solutions to reduce latency and improve global content delivery performance.', 'Architecture & Design', '2024–Present', 1, 'Architected edge computing solutions using Cloudflare Workers and D1', 'Reduced latency and improved global content delivery performance', 'Achieved sub-50ms response times globally with zero-cost serverless hosting', 'CV Skills Assistant on Cloudflare Edge');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (8, 'microservices-principles-1', 'Microservices Principles', '5+ years', 5, 85, 'Advanced', 'Applied microservices principles over 5+ years to decompose systems into independently deployable, loosely-coupled services.', 'Architecture & Design', NULL, 1, 'Applied microservices principles to decompose enterprise systems', 'Created independently deployable, loosely-coupled services', 'Improved system resilience and enabled polyglot technology adoption', 'CCHQ national campaign platform');

-- Frontend Development
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (9, 'angular-1', 'Angular', '3+ years', 3, 85, 'Advanced', 'Developed enterprise Angular applications for 3+ years, leveraging reactive patterns and modular component design.', 'Frontend Development', NULL, 2, 'Developed enterprise Angular applications with reactive RxJS patterns', 'Enabled real-time UI updates and improved user experience', 'Delivered responsive SPAs with 40% faster load times', 'CCHQ campaign management dashboard');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (10, 'rxjs-1', 'RxJS', '3+ years', 3, 85, 'Advanced', 'Utilized RxJS for 3+ years to manage asynchronous data streams and event-driven interactions in Angular applications.', 'Frontend Development', NULL, 2, 'Implemented reactive programming patterns with RxJS observables', 'Simplified complex asynchronous UI workflows and state management', 'Reduced callback complexity by 70% and improved code maintainability', 'CCHQ national campaign platform');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (11, 'typescript-1', 'TypeScript', '6+ years', 6, 88, 'Advanced', 'Wrote type-safe applications with TypeScript for 6+ years, improving code quality and developer experience.', 'Frontend Development', NULL, 2, 'Adopted TypeScript across all frontend codebases with strict type checking', 'Caught errors at compile time and improved IDE intellisense', 'Reduced runtime errors by 60% and improved developer productivity', 'CCHQ national campaign platform');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (12, 'javascript-1', 'JavaScript', '19 years', 19, 95, 'Expert', 'Core JavaScript expertise spanning 19 years, building interactive web applications and modern frontend solutions.', 'Frontend Development', NULL, 2, 'Built interactive web applications using core JavaScript and modern ES6+ features', 'Delivered rich user experiences across browsers', 'Maintained consistent 95%+ user satisfaction scores across 19 years of projects', 'CCHQ national campaign platform, Wairbut enterprise systems');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (13, 'angularjs-1', 'AngularJS', '10 years', 10, 90, 'Expert', 'Built and maintained AngularJS applications over 10 years, delivering dynamic SPAs for enterprise clients.', 'Frontend Development', NULL, 2, 'Built and maintained large-scale AngularJS applications', 'Delivered dynamic single-page applications for enterprise clients', 'Supported 100,000+ daily active users across multiple platforms', 'CCHQ national campaign platform');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (14, 'bootstrap-1', 'Bootstrap', '8+ years', 8, 85, 'Advanced', 'Designed responsive, mobile-first interfaces with Bootstrap for 8+ years, accelerating UI development.', 'Frontend Development', NULL, 2, 'Designed responsive mobile-first interfaces using Bootstrap framework', 'Accelerated UI development and ensured cross-device compatibility', 'Reduced UI development time by 50% while maintaining design consistency', 'CCHQ national campaign platform');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (15, 'clarity-design-1', 'Clarity Design', '2025-Present', 1, 80, 'Advanced', 'Adopted Clarity Design System for modern Angular applications, ensuring consistent and accessible UI patterns.', 'Frontend Development', '2025–Present', 2, 'Adopted VMware Clarity Design System for enterprise Angular applications', 'Ensured consistent, accessible UI patterns aligned with enterprise standards', 'Achieved WCAG 2.1 AA compliance and improved design consistency', 'Independent Production');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (16, 'playwright-1', 'Playwright', '2024-Present', 2, 40, 'Intermediate', 'Implemented end-to-end tests with Playwright to validate cross-browser functionality and UI behavior.', 'Frontend Development', '2024–Present', 2, 'Implemented end-to-end testing with Playwright across Chrome, Firefox, and Safari', 'Validated cross-browser functionality and automated UI regression testing', 'Caught 95% of UI bugs before production deployment', 'CCHQ national campaign platform');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (17, 'react-with-typescript-1', 'React with TypeScript', 'Development/Research', 1, 75, 'Advanced', 'Explored React with TypeScript through development and research, building component-based prototypes.', 'Frontend Development', NULL, 2, 'Built component-based prototypes using React hooks and TypeScript type safety', 'Evaluated modern functional component patterns and hooks ecosystem', 'Informed future frontend architecture decisions and interoperability with Angular', 'Prototype Development');

-- Backend Development
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (18, 'csharp-1', 'C#', '19 years', 19, 95, 'Expert', 'Deep expertise in C# spanning 19 years, delivering enterprise-grade backend systems and services.', 'Backend Development', NULL, 3, 'Developed enterprise-grade backend systems using C# across 19 years', 'Delivered scalable, maintainable services for mission-critical applications', 'Supported systems processing millions of transactions daily', 'CCHQ national campaign platform, Wairbut enterprise systems');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (19, 'aspnet-core-1', 'ASP.NET Core', '5+ years', 5, 90, 'Expert', 'Developed high-performance ASP.NET Core APIs and web applications for 5+ years, supporting modern cloud deployments.', 'Backend Development', NULL, 3, 'Developed high-performance ASP.NET Core REST APIs with dependency injection', 'Enabled cloud-native deployments and horizontal scaling', 'Supported 10,000+ concurrent users with sub-100ms response times', 'CCHQ national campaign platform');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (20, 'dotnet-6plus-1', '.NET 6+', '3+ years', 3, 85, 'Advanced', 'Built modern .NET 6+ applications for 3+ years, leveraging latest framework features and performance improvements.', 'Backend Development', NULL, 3, 'Migrated legacy applications to .NET 6+ leveraging minimal APIs and improved performance', 'Improved startup time and reduced memory footprint', 'Achieved 30% performance improvement and 40% reduction in hosting costs', 'CCHQ national campaign platform');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (21, 'restful-apis-2', 'RESTful APIs', '10+ years', 10, 90, 'Expert', 'Built and maintained RESTful APIs for 10+ years, enabling seamless integration and scalable backend architecture.', 'Backend Development', NULL, 3, 'Architected and maintained 50+ RESTful APIs with comprehensive OpenAPI documentation across enterprise systems', 'Enabled consistent API contracts and seamless system integration', 'Reduced integration complexity by 70% and supported 100+ external integrations', 'CCHQ national campaign platform');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (22, 'full-stack-service-architecture-1', 'Full-Stack Service Architecture', '5+ years (CCHQ)', 5, 85, 'Advanced', 'Architected full-stack services at CCHQ over 5+ years, enabling autonomous teams and streamlined service ownership.', 'Backend Development', NULL, 3, 'Designed autonomous full-stack services with dedicated front-end and back-end teams', 'Enabled independent team ownership and service deployment autonomy', 'Reduced coordination overhead and increased deployment velocity', 'CCHQ national campaign platform');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (23, 'windows-services-1', 'Windows Services', '8+ years (thousands records/sec)', 8, 85, 'Advanced', 'Developed high-throughput Windows Services for 8+ years, processing thousands of records per second reliably.', 'Backend Development', NULL, 3, 'Developed fault-tolerant Windows Services with MSMQ and SQL-based queuing', 'Enabled reliable high-throughput asynchronous processing', 'Processed thousands of records per second with 99.9% reliability', 'CCHQ national campaign platform');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (24, 'msmq-sql-based-queues-1', 'MSMQ & SQL-based Queues', '8+ years', 8, 85, 'Advanced', 'Implemented reliable message queuing with MSMQ and SQL-based queues over 8+ years, ensuring fault-tolerant processing.', 'Backend Development', NULL, 3, 'Implemented distributed message queuing with automatic retry, dead-letter handling, and transaction support', 'Ensured reliable asynchronous processing and fault-tolerance at scale', 'Achieved 99.9% message delivery with zero message loss across millions of transactions', 'CCHQ national campaign platform');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (25, 'nodejs-1', 'Node.js', '2025', 1, 80, 'Advanced', 'Built serverless and backend services with Node.js, leveraging JavaScript for full-stack development.', 'Backend Development', '2025–Present', 3, 'Built serverless backend services with Node.js and TypeScript', 'Leveraged JavaScript for full-stack development consistency', 'Enabled rapid prototyping and reduced technology context switching', 'Independent Production');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (26, 'azure-functions-nodejs-typescript-1', 'Azure Functions (Node.js/TypeScript)', '2025', 1, 85, 'Advanced', 'Deployed serverless Azure Functions using Node.js and TypeScript for scalable, event-driven backend processing.', 'Backend Development', '2025–Present', 3, 'Deployed serverless Azure Functions with Node.js and TypeScript', 'Enabled event-driven, auto-scaling backend processing', 'Reduced infrastructure costs by 80% vs. always-on servers', 'Independent Production');

-- Database & Performance
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (27, 'sql-server-1', 'SQL Server', '20+ years', 20, 95, 'Expert', 'Expert-level SQL Server administration and development over 20+ years, supporting mission-critical enterprise databases.', 'Database & Performance', NULL, 4, 'Administered mission-critical SQL Server databases with backup, recovery, and high availability', 'Ensured 99.9% uptime and data integrity', 'Zero data loss incidents over 20 years of enterprise database management', 'CCHQ national campaign platform, Wairbut enterprise systems');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (28, 'tsql-performance-tuning-1', 'T-SQL Performance Tuning', '20+ years', 20, 95, 'Expert', 'Optimized T-SQL queries and database performance for 20+ years, achieving significant response time and throughput gains.', 'Database & Performance', NULL, 4, 'Optimized complex T-SQL queries and database indexes', 'Improved query response times and throughput capacity', 'Achieved 10x performance gains on key queries supporting thousands of records per second', 'CCHQ national campaign platform, Wairbut enterprise systems');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (29, 'daab-enterprise-library-1', 'DAAB/Enterprise Library', '11+ years', 11, 90, 'Expert', 'Utilized Data Access Application Block and Enterprise Library for 11+ years, standardizing enterprise data access patterns.', 'Database & Performance', NULL, 4, 'Standardized data access patterns using DAAB and Enterprise Library configuration patterns across all applications', 'Unified logging, caching, validation, and configuration management across teams', 'Reduced code duplication by 60% and improved consistency across enterprise systems at CCHQ and Wairbut', 'CCHQ national campaign platform, Wairbut enterprise systems');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (30, 'entity-framework-4-1', 'Entity Framework 4', '5 years total (discontinued after 2)', 5, 70, 'Intermediate', 'Applied Entity Framework 4 for ORM-based data access before discontinuing use after 2 years due to project constraints.', 'Database & Performance', NULL, 4, 'Implemented ORM-based data access using Entity Framework 4 with LINQ queries and lazy loading', 'Abstracted database complexity and improved code maintainability', 'Standardized entity mapping across CCHQ and Wairbut projects before pivoting to DAAB for performance', 'CCHQ national campaign platform, Wairbut enterprise systems');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (31, 'oracle-1', 'Oracle', '5+ years', 5, 75, 'Advanced', 'Worked with Oracle databases for 5+ years, managing data storage and complex queries for enterprise applications.', 'Database & Performance', NULL, 4, 'Managed Oracle database instances with complex T-SQL equivalent PL/SQL queries and optimization', 'Enabled complex transaction management and large-scale data processing', 'Supported millions of transactions per day at Wairbut with sub-100ms response times', 'Wairbut enterprise systems');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (32, 'azure-cosmos-db-1', 'Azure Cosmos DB', '2025', 1, 80, 'Advanced', 'Integrated Azure Cosmos DB for globally distributed, low-latency NoSQL data storage in cloud-native applications.', 'Database & Performance', '2025–Present', 4, 'Integrated Azure Cosmos DB for globally distributed NoSQL storage', 'Enabled low-latency data access across multiple regions', 'Achieved sub-10ms read latency globally with automatic multi-region replication', 'Independent Production');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (33, 'mongodb-api-1', 'MongoDB API', '2025', 1, 75, 'Advanced', 'Leveraged MongoDB API with Cosmos DB for flexible, document-based data modeling in modern serverless solutions.', 'Database & Performance', '2025–Present', 4, 'Implemented document-based NoSQL queries using MongoDB API compatibility layer with Azure Cosmos DB', 'Enabled flexible schema design and horizontal scaling', 'Simplified data modeling for semi-structured data with automatic multi-region replication', 'Independent Production');

-- Cloud & DevOps
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (34, 'azure-devops-1', 'Azure DevOps', '5+ years', 5, 85, 'Advanced', 'Managed CI/CD pipelines and project workflows with Azure DevOps for 5+ years, streamlining release automation.', 'Cloud & DevOps', NULL, 5, 'Designed and implemented automated CI/CD pipelines in Azure DevOps', 'Streamlined build, test, and deployment automation', 'Cut deployment time by 75% and eliminated manual deployment errors', 'CCHQ national campaign platform');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (35, 'azure-blob-storage-1', 'Azure Blob Storage', '5+ years', 5, 85, 'Advanced', 'Utilized Azure Blob Storage for 5+ years to store and serve large files and media content reliably.', 'Cloud & DevOps', NULL, 5, 'Implemented Azure Blob Storage with tiered access levels and lifecycle policies for media management', 'Enabled scalable content delivery and cost-optimized storage tiers', 'Reduced storage costs by 40% while improving content delivery performance at CCHQ', 'CCHQ national campaign platform');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (36, 'azure-cognitive-services-1', 'Azure Cognitive Services', '3+ years', 3, 75, 'Advanced', 'Integrated Azure Cognitive Services for 3+ years, adding AI capabilities like vision and natural language processing.', 'Cloud & DevOps', NULL, 5, 'Integrated Computer Vision and Text Analytics for intelligent content processing', 'Enabled automated image classification and sentiment analysis workflows', 'Reduced manual content moderation overhead by 70% at CCHQ', 'CCHQ national campaign platform');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (37, 'azure-static-web-apps-1', 'Azure Static Web Apps', '2024-Present', 1, 85, 'Advanced', 'Deployed modern web applications using Azure Static Web Apps, leveraging global CDN and integrated backend APIs.', 'Cloud & DevOps', '2024–Present', 5, 'Deployed static web applications using Azure Static Web Apps', 'Leveraged global CDN and integrated serverless API backends', 'Achieved 99.95% uptime with automatic SSL and global edge distribution', 'Independent Production');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (38, 'azure-cdn-1', 'Azure CDN', '3+ years', 3, 75, 'Advanced', 'Configured Azure CDN for 3+ years to accelerate content delivery and reduce latency for global users.', 'Cloud & DevOps', NULL, 5, 'Configured Azure CDN with caching policies and query string handling for static and dynamic content', 'Reduced content delivery latency and improved global performance', 'Achieved 50% improvement in page load times for CCHQ campaign platforms globally', 'CCHQ national campaign platform');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (39, 'git-1', 'Git', '8+ years', 8, 85, 'Advanced', 'Managed source control with Git for 8+ years, supporting collaborative development and branching strategies.', 'Cloud & DevOps', NULL, 5, 'Managed distributed source control with Git using GitFlow and trunk-based development strategies', 'Enabled collaborative development with code review and branching workflows', 'Supported 100+ developers with zero merge conflicts through proper branch management across CCHQ and Wairbut', 'CCHQ national campaign platform, Wairbut enterprise systems');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (40, 'cicd-pipelines-1', 'CI/CD Pipelines', '5+ years', 5, 80, 'Advanced', 'Designed and maintained CI/CD pipelines for 5+ years, automating build, test, and deployment workflows.', 'Cloud & DevOps', NULL, 5, 'Designed automated build, test, and deployment pipelines using Azure DevOps and TFS', 'Eliminated manual deployment processes and enabled continuous integration', 'Reduced deployment time by 75% and improved deployment frequency to daily releases at CCHQ', 'CCHQ national campaign platform');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (41, 'appdynamics-1', 'AppDynamics', '9+ years', 9, 80, 'Advanced', 'Monitored application performance with AppDynamics for 9+ years, identifying bottlenecks and improving user experience.', 'Cloud & DevOps', NULL, 5, 'Implemented comprehensive application performance monitoring with transaction tracing and alerting', 'Enabled real-time visibility into system performance and automated incident alerting', 'Reduced mean-time-to-resolution by 80% and improved system reliability at CCHQ', 'CCHQ national campaign platform');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (42, 'terraform-1', 'Terraform', '1+ years', 1, 80, 'Advanced', 'Adopted Terraform for infrastructure as code, enabling repeatable and version-controlled cloud provisioning.', 'Cloud & DevOps', NULL, 5, 'Implemented infrastructure-as-code using Terraform with state management and modular configurations', 'Enabled version-controlled, repeatable infrastructure deployments', 'Reduced infrastructure provisioning time by 85% and eliminated manual configuration drift', 'Independent Production');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (43, 'cloudflare-dns-cdn-1', 'Cloudflare DNS/CDN', '2024-Present', 1, 80, 'Advanced', 'Leveraged Cloudflare DNS and CDN for fast, secure global content delivery with DDoS protection.', 'Cloud & DevOps', '2024–Present', 5, 'Configured Cloudflare DNS and CDN with caching rules and DDoS protection for global edge delivery', 'Enabled ultra-fast content delivery with built-in security filtering', 'Achieved sub-100ms global response times with DDoS and bot protection', 'Independent Production');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (44, 'cloudflare-workers-1', 'Cloudflare Workers', '2024-Present (Production)', 1, 85, 'Advanced', 'Deployed serverless edge functions with Cloudflare Workers in production, achieving zero-cost hosting and low latency.', 'Cloud & DevOps', '2024–Present', 5, 'Deployed serverless edge functions with Cloudflare Workers in production', 'Eliminated infrastructure management and server costs', 'Achieved zero-cost hosting with global low latency under 50ms', 'CV Skills Assistant and edge API services');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (45, 'cloudflare-pages-1', 'Cloudflare Pages', '2024-Present (Production)', 1, 85, 'Advanced', 'Published static sites with Cloudflare Pages in production, integrating seamless Git-based deployments.', 'Cloud & DevOps', '2024–Present', 5, 'Published static sites with Cloudflare Pages using Git-based deployments', 'Enabled automatic deployments on every commit', 'Achieved zero downtime deployments with instant rollback capability', 'Independent Production');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (46, 'azure-functions-nodejs-typescript-2', 'Azure Functions (Node.js/TypeScript)', '2025', 1, 85, 'Advanced', 'Deployed serverless Azure Functions with Node.js and TypeScript for event-driven, scalable backend workloads.', 'Cloud & DevOps', '2025–Present', 5, 'Deployed production serverless functions with HTTP triggers, timers, and queue-based event processing', 'Enabled auto-scaling and event-driven backend processing without server management', 'Reduced infrastructure costs by 80% compared to dedicated servers while maintaining performance SLAs', 'Independent Production');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (47, 'playwright-testing-1', 'Playwright Testing', '2024-Present', 2, 40, 'Intermediate', 'Implemented Playwright for end-to-end testing, validating application behavior across multiple browsers.', 'Cloud & DevOps', '2024–Present', 5, 'Implemented cross-browser end-to-end tests using Playwright with parallel execution', 'Automated UI regression testing across Chrome, Firefox, and Safari browsers', 'Caught 95% of UI bugs before production and reduced manual testing overhead by 70%', 'CCHQ national campaign platform');

-- Modern Development Practices
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (48, 'serverless-architecture-1', 'Serverless Architecture', '2025', 1, 85, 'Advanced', 'Designed serverless architectures to eliminate infrastructure management and reduce operational costs.', 'Modern Development Practices', '2025–Present', 6, 'Designed serverless architectures using Azure Functions and Cloudflare Workers', 'Eliminated infrastructure management and reduced operational costs', 'Cut infrastructure costs by 85% while improving scalability', 'Independent Production');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (49, 'low-cost-infrastructure-design-1', 'Low-Cost Infrastructure Design', '2024-Present', 1, 85, 'Advanced', 'Architected cost-efficient infrastructure solutions, minimizing cloud spend while maintaining performance and scalability.', 'Modern Development Practices', '2024–Present', 6, 'Architected cost-efficient infrastructure using free-tier and serverless services', 'Minimized cloud spend while maintaining performance and scalability', 'Reduced monthly infrastructure costs from $500+ to under $10', 'Independent Production');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (50, 'azure-static-web-apps-2', 'Azure Static Web Apps', '2024-Present', 1, 85, 'Advanced', 'Deployed static web applications using Azure Static Web Apps for simplified hosting and integrated APIs.', 'Modern Development Practices', '2024–Present', 6, 'Deployed static web applications with integrated serverless API backends and automatic SSL', 'Eliminated server management and enabled continuous deployment from Git', 'Achieved 99.95% uptime with zero infrastructure maintenance overhead', 'Independent Production');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (51, 'cloudflare-dns-cdn-2', 'Cloudflare DNS/CDN', '2024-Present', 1, 80, 'Advanced', 'Utilized Cloudflare DNS and CDN for secure, high-performance content delivery with built-in security features.', 'Modern Development Practices', '2024–Present', 6, 'Configured Cloudflare DNS with security policies, bot management, and edge caching for cost-effective delivery', 'Minimized infrastructure costs while providing DDoS protection and global CDN', 'Reduced monthly CDN costs to under $5 with premium DDoS protection included', 'Independent Production');

-- Technical Research & Prototyping
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (52, 'containerization-orchestration-1', 'Containerization & Orchestration', 'Docker, Kubernetes (pod replicas, self-healing)', 1, 75, 'Advanced', 'Prototyped containerized applications with Docker and Kubernetes, exploring self-healing and scalable pod orchestration.', 'Technical Research & Prototyping', NULL, 7, 'Prototyped microservices containerization using Docker with Kubernetes pod replicas and self-healing policies', 'Evaluated container orchestration for auto-scaling and fault-tolerance', 'Validated Kubernetes architecture approach for future high-availability deployments', 'Prototype Development');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (53, 'message-brokers-patterns-1', 'Message Brokers & Patterns', 'RabbitMQ (pub/sub patterns)', 1, 75, 'Advanced', 'Researched RabbitMQ pub/sub patterns for decoupled messaging and event-driven architecture prototypes.', 'Technical Research & Prototyping', NULL, 7, 'Researched RabbitMQ publish/subscribe patterns for event-driven microservices architecture', 'Evaluated decoupled messaging approaches to complement existing MSMQ infrastructure', 'Identified RabbitMQ as alternative for cloud-native event-driven systems', 'Prototype Development');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (54, 'distributed-caching-1', 'Distributed Caching', 'Redis', 1, 70, 'Advanced', 'Experimented with Redis for distributed caching to improve application performance and reduce database load.', 'Technical Research & Prototyping', NULL, 7, 'Prototyped Redis distributed caching with key expiration and cache invalidation strategies', 'Evaluated caching approaches to reduce database load and improve response times', 'Identified Redis pattern for future performance optimization in cloud-native applications', 'Prototype Development');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (55, 'concurrency-models-1', 'Concurrency Models', 'Akka.NET (Actor Model)', 1, 70, 'Advanced', 'Explored Akka.NET''s actor model for building concurrent, fault-tolerant systems with message-driven architecture.', 'Technical Research & Prototyping', NULL, 7, 'Researched Akka.NET actor model for concurrent, fault-tolerant message-driven systems', 'Evaluated actor-based concurrency as alternative to traditional threading models', 'Identified actor model applicability for highly concurrent backend services', 'Prototype Development');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (56, 'frontend-frameworks-1', 'Frontend Frameworks', 'React, Bootstrap, Clarity Design', 1, 75, 'Advanced', 'Researched and prototyped with React, Bootstrap, and Clarity Design for modern, component-based UI development.', 'Technical Research & Prototyping', NULL, 7, 'Prototyped modern frontend frameworks including React, Bootstrap, and VMware Clarity Design System', 'Evaluated modern UI frameworks for consistency with existing Angular development', 'Informed frontend technology choices and identified component reusability patterns', 'Independent Production');

-- Edge Architectures (Production)
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (57, 'cloudflare-workers-2', 'Cloudflare Workers', 'Globally distributed, zero‑cost hosting', 1, 85, 'Advanced', 'Deployed production Cloudflare Workers for globally distributed, zero-cost edge compute with minimal latency.', 'Edge Architectures (Production)', '2024–Present', 8, 'Deployed serverless edge functions with Cloudflare Workers across global data centers', 'Eliminated server infrastructure and reduced latency to sub-50ms globally', 'Achieved zero-cost hosting with 99.95% uptime and global low-latency compute', 'CV Skills Assistant and edge API services');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (58, 'ai-powered-cv-assistant-1', 'AI‑Powered CV Assistant', '2024–Present', 1, 85, 'Advanced', 'Designed and operated an AI‑powered CV assistant running on Cloudflare Workers with semantic search and vector storage.', 'Edge Architectures (Production)', NULL, 8, 'Designed and deployed on Cloudflare Workers AI with semantic search and vector storage', 'Delivered production-grade, low-latency AI features at the edge', 'Production-grade deployment supporting CV search and enrichment on Cloudflare Edge', 'CV Skills Assistant on Cloudflare Edge');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (59, 'cloudflare-pages-2', 'Cloudflare Pages', 'Technical blog deployment', 1, 85, 'Advanced', 'Published technical blog using Cloudflare Pages for fast, globally distributed static site hosting.', 'Edge Architectures (Production)', '2024–Present', 8, 'Published static sites using Cloudflare Pages with Git-based CI/CD and preview deployments', 'Enabled instant deployments with zero-downtime and automatic SSL across all edge locations', 'Achieved sub-second global page load times with zero infrastructure cost', 'Independent Production');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (60, 'infrastructure-as-code-1', 'Infrastructure as Code', 'Terraform‑based workflows (Exploratory)', 1, 65, 'Intermediate', 'Explored Terraform-based infrastructure workflows to automate provisioning and version-control cloud resources.', 'Edge Architectures (Production)', NULL, 8, 'Explored Terraform infrastructure-as-code patterns for Cloudflare and Azure resource provisioning', 'Evaluated IaC approaches for reproducible edge and cloud infrastructure', 'Established foundation for version-controlled infrastructure management', 'Independent Production');

-- Legacy Development
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (61, 'vbnet-1', 'VB.NET', '8+ years', 8, 90, 'Expert', 'Maintained and extended VB.NET enterprise applications for 8+ years, supporting legacy systems and migrations.', 'Legacy Development', NULL, 9, 'Maintained and enhanced VB.NET enterprise applications across multiple versions', 'Enabled long-term support for legacy systems and facilitated C# migrations', 'Sustained 8 years of stable production operation at Wairbut with zero critical issues', 'Wairbut enterprise systems');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (62, 'wpf-1', 'WPF', '8+ years', 8, 85, 'Advanced', 'Developed Windows Presentation Foundation desktop applications for 8+ years with rich, data-bound UIs.', 'Legacy Development', NULL, 9, 'Developed data-bound WPF desktop applications with XAML styling and MVVM patterns', 'Enabled rich Windows desktop experiences with consistent branding and workflows', 'Delivered responsive desktop applications supporting 100,000+ users at CCHQ and Wairbut', 'CCHQ national campaign platform, Wairbut enterprise systems');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (63, 'silverlight-1', 'Silverlight', '5+ years', 5, 80, 'Advanced', 'Built Silverlight-based rich internet applications for 5+ years before platform deprecation.', 'Legacy Development', NULL, 9, 'Built rich internet applications using Silverlight with data bindings and animations', 'Delivered interactive client-side experiences before HTML5 standards maturity', 'Successfully migrated 5+ applications from Silverlight to web standards at Wairbut', 'Wairbut enterprise systems');
INSERT INTO technology (id, stable_id, name, experience, experience_years, proficiency_percent, level, summary, category, recency, category_id, action, effect, outcome, related_project) VALUES (64, 'aspnet-mvc-webforms-1', 'ASP.NET MVC/WebForms', '8+ years', 8, 85, 'Advanced', 'Developed and maintained ASP.NET MVC and WebForms applications for 8+ years, supporting enterprise web solutions.', 'Legacy Development', NULL, 9, 'Built MVC and WebForms applications with server-side and client-side validation', 'Enabled server-centric web development for enterprise workflows', 'Supported 100,000+ daily active users across multiple applications at CCHQ and Wairbut', 'CCHQ national campaign platform, Wairbut enterprise systems');

-- Note: Vector embeddings will be generated separately via Worker
