-- Missing CV skills seeding script for D1 database
-- Run with: npx wrangler d1 execute cv_assistant_db --remote --yes --file=./scripts/seed-cv-skills.sql

-- Languages & Frameworks
INSERT INTO technology (stable_id, name, category, experience, experience_years, proficiency_percent, level, action, effect, outcome, employer, recency) VALUES ('go-1', 'Go', 'Backend Development', 'Used Go for GCP Cloud Functions runtime, implementing webhook receivers with HMAC validation and Firestore integration', 2, 10, 'Intermediate', 'Implemented GCP Cloud Function webhook receiver', 'Validated HMAC signatures and wrote to Firestore', 'Achieved sub-second cross-cloud data flow', 'Portfolio', 'Current (2023-2025)');

INSERT INTO technology (stable_id, name, category, experience, experience_years, proficiency_percent, level, action, effect, outcome, employer, recency) VALUES ('react-1', 'React', 'Frontend Development', 'Built real-time analytics dashboard using React with TypeScript, implementing Firestore WebSocket listeners for instant updates', 3, 15, 'Advanced', 'Architected real-time dashboard with Firestore onSnapshot()', 'Eliminated polling overhead', 'Sub-second UI updates across cloud boundaries', 'Portfolio', 'Current (2023-2025)');

INSERT INTO technology (stable_id, name, category, experience, experience_years, proficiency_percent, level, action, effect, outcome, employer) VALUES ('dotnet-core-1', '.NET Core', 'Backend Development', 'Developed ASP.NET Core APIs and services for enterprise platforms, migrating from .NET Framework to modern .NET Core/5+', 8, 40, 'Expert', 'Migrated legacy systems to .NET Core', 'Enabled cross-platform deployment', 'Reduced infrastructure costs', 'CCHQ');

INSERT INTO technology (stable_id, name, category, experience, experience_years, proficiency_percent, level, action, effect, outcome, employer) VALUES ('aspnet-mvc-1', 'ASP.NET MVC', 'Backend Development', 'Built enterprise web applications using ASP.NET MVC, later evolved to Angular SPAs with ASP.NET Core backends', 15, 75, 'Expert', 'Architected layered MVC applications', 'Separated concerns for maintainability', 'Enabled independent frontend evolution', 'CCHQ');

INSERT INTO technology (stable_id, name, category, experience, experience_years, proficiency_percent, level, action, effect, outcome, employer) VALUES ('entity-framework-1', 'Entity Framework', 'Backend Development', 'Implemented data access layer using Entity Framework Code-First and Database-First approaches, optimizing LINQ queries for performance', 12, 60, 'Expert', 'Designed EF data models with navigation properties', 'Simplified data access with strongly-typed queries', '3× query performance improvement with proper indexing', 'CCHQ');

-- Cloud Services (AWS)
INSERT INTO technology (stable_id, name, category, experience, experience_years, proficiency_percent, level, action, effect, outcome, employer, recency) VALUES ('aws-lambda-1', 'AWS Lambda', 'Cloud & DevOps', 'Engineered event-driven Lambda functions with SQS FIFO batching, achieving 12ms P99 latency and 10:1 cost optimization', 3, 15, 'Advanced', 'Implemented Lambda batch processing with SQS FIFO', 'Reduced invocations from 3,000 to 300/month', '90% cost reduction through batching', 'Portfolio', 'Current (2023-2025)');

INSERT INTO technology (stable_id, name, category, experience, experience_years, proficiency_percent, level, action, effect, outcome, employer, recency) VALUES ('aws-dynamodb-1', 'AWS DynamoDB', 'Cloud & DevOps', 'Designed DynamoDB schema with DynamoDB Streams for event sourcing, implementing TTL for automatic data expiry', 3, 15, 'Advanced', 'Architected DynamoDB with Streams + TTL', 'Enabled fire-and-forget writes with async processing', '12ms P99 latency with £0 operational cost', 'Portfolio', 'Current (2023-2025)');

INSERT INTO technology (stable_id, name, category, experience, experience_years, proficiency_percent, level, action, effect, outcome, employer, recency) VALUES ('aws-sqs-1', 'AWS SQS FIFO', 'Cloud & DevOps', 'Implemented SQS FIFO queues for reliable message processing, enabling 10:1 batching optimization in Lambda', 3, 15, 'Advanced', 'Designed SQS FIFO queue with batch processing', 'Guaranteed message ordering with deduplication', 'Reduced Lambda invocations by 90%', 'Portfolio', 'Current (2023-2025)');

INSERT INTO technology (stable_id, name, category, experience, experience_years, proficiency_percent, level, action, effect, outcome, employer, recency) VALUES ('aws-eventbridge-1', 'AWS EventBridge', 'Cloud & DevOps', 'Configured EventBridge cron schedules for weekly analytics reporting, triggering Lambda functions with SES email delivery', 2, 10, 'Intermediate', 'Set up EventBridge cron for automated reporting', 'Scheduled weekly email digests', '4 automated reports/month at £0 cost', 'Portfolio', 'Current (2023-2025)');

INSERT INTO technology (stable_id, name, category, experience, experience_years, proficiency_percent, level, action, effect, outcome, employer, recency) VALUES ('aws-ses-1', 'AWS SES', 'Cloud & DevOps', 'Integrated SES for automated email delivery in analytics pipeline, sending weekly reports with formatted HTML', 2, 10, 'Intermediate', 'Configured SES for automated emails', 'Delivered weekly analytics reports', 'Reliable email delivery within free tier', 'Portfolio', 'Current (2023-2025)');

INSERT INTO technology (stable_id, name, category, experience, experience_years, proficiency_percent, level, action, effect, outcome, employer, recency) VALUES ('dynamodb-streams-1', 'DynamoDB Streams', 'Cloud & DevOps', 'Architected event-driven pipeline using DynamoDB Streams to trigger Lambda processing asynchronously', 2, 10, 'Advanced', 'Configured DynamoDB Streams with Lambda trigger', 'Decoupled write operations from processing', 'Fire-and-forget pattern with 12ms write latency', 'Portfolio', 'Current (2023-2025)');

-- Cloud Services (GCP)
INSERT INTO technology (stable_id, name, category, experience, experience_years, proficiency_percent, level, action, effect, outcome, employer, recency) VALUES ('gcp-cloud-functions-1', 'GCP Cloud Functions', 'Cloud & DevOps', 'Deployed Go-based Cloud Functions for webhook receivers, implementing HMAC validation and Firestore writes', 2, 10, 'Intermediate', 'Implemented webhook validation with HMAC-SHA256', 'Secured cross-cloud data flow from AWS to GCP', 'Sub-second cross-cloud pipeline', 'Portfolio', 'Current (2023-2025)');

INSERT INTO technology (stable_id, name, category, experience, experience_years, proficiency_percent, level, action, effect, outcome, employer, recency) VALUES ('gcp-firestore-1', 'GCP Firestore', 'Cloud & DevOps', 'Architected real-time Firestore database with WebSocket listeners, enabling instant dashboard updates', 2, 10, 'Intermediate', 'Designed Firestore schema with real-time listeners', 'Eliminated polling with WebSocket updates', 'Sub-second UI synchronization', 'Portfolio', 'Current (2023-2025)');

INSERT INTO technology (stable_id, name, category, experience, experience_years, proficiency_percent, level, action, effect, outcome, employer, recency) VALUES ('firebase-hosting-1', 'Firebase Hosting', 'Cloud & DevOps', 'Deployed React dashboard to Firebase Hosting with global CDN distribution', 2, 10, 'Intermediate', 'Configured Firebase Hosting with GitHub Actions CI/CD', 'Global edge distribution', 'Fast dashboard loads worldwide', 'Portfolio', 'Current (2023-2025)');

-- Cloud Services (Cloudflare - new ones only, Pages/Workers already exist)
INSERT INTO technology (stable_id, name, category, experience, experience_years, proficiency_percent, level, action, effect, outcome, employer, recency) VALUES ('cloudflare-kv-1', 'Cloudflare KV', 'Cloud & DevOps', 'Implemented edge caching with Cloudflare KV for quota tracking and session management', 2, 10, 'Intermediate', 'Designed KV-based quota system', 'Edge-native state management', 'Sub-10ms quota checks', 'Portfolio', 'Current (2023-2025)');

INSERT INTO technology (stable_id, name, category, experience, experience_years, proficiency_percent, level, action, effect, outcome, employer, recency) VALUES ('cloudflare-d1-1', 'Cloudflare D1', 'Cloud & DevOps', 'Migrated from linear search to Vectorize, using D1 for metadata storage', 1, 5, 'Intermediate', 'Designed D1 schema for skill metadata', 'Centralized metadata with edge access', '12ms query latency', 'Portfolio', 'Current (2023-2025)');

INSERT INTO technology (stable_id, name, category, experience, experience_years, proficiency_percent, level, action, effect, outcome, employer, recency) VALUES ('cloudflare-vectorize-1', 'Cloudflare Vectorize', 'Cloud & DevOps', 'Implemented semantic search using Vectorize with HNSW index, achieving 64-vector indexing', 1, 5, 'Intermediate', 'Indexed 768-dimensional embeddings', 'Enabled natural language skill queries', 'Semantic search with 12ms latency', 'Portfolio', 'Current (2023-2025)');

INSERT INTO technology (stable_id, name, category, experience, experience_years, proficiency_percent, level, action, effect, outcome, employer, recency) VALUES ('workers-ai-1', 'Workers AI', 'Cloud & DevOps', 'Integrated Workers AI for embedding generation at the edge, using BGE-base-en-v1.5 model', 1, 5, 'Intermediate', 'Implemented edge-native embedding generation', 'No external API calls for embeddings', 'Complete semantic search in <50ms', 'Portfolio', 'Current (2023-2025)');

-- Cloud Services (Azure - azure-cosmos-db-1 already exists, skipping CosmosDB)

-- Databases (sql-server-1 already exists, skipping)

-- Infrastructure & DevOps
INSERT INTO technology (stable_id, name, category, experience, experience_years, proficiency_percent, level, action, effect, outcome, employer) VALUES ('docker-1', 'Docker', 'Cloud & DevOps', 'Containerized applications with Docker for consistent deployments across environments', 5, 25, 'Advanced', 'Created Docker images for microservices', 'Eliminated environment inconsistencies', 'Repeatable deployments across dev/staging/prod', 'CCHQ');

INSERT INTO technology (stable_id, name, category, experience, experience_years, proficiency_percent, level, action, effect, outcome, employer) VALUES ('kubernetes-1', 'Kubernetes', 'Cloud & DevOps', 'Prototyped Kubernetes deployments for container orchestration, evaluated for CCHQ platform evolution', 2, 10, 'Intermediate', 'Deployed test clusters with K8s', 'Explored auto-scaling and self-healing', 'Informed platform architecture decisions', 'CCHQ');

INSERT INTO technology (stable_id, name, category, experience, experience_years, proficiency_percent, level, action, effect, outcome, employer, recency) VALUES ('github-actions-1', 'GitHub Actions', 'Cloud & DevOps', 'Built 6 parallel CI/CD pipelines deploying to 3 cloud providers with semantic versioning', 3, 15, 'Advanced', 'Architected independent GitHub Actions workflows', 'Enabled autonomous microservice deployments', '6 services with independent release cycles', 'Portfolio', 'Current (2023-2025)');

INSERT INTO technology (stable_id, name, category, experience, experience_years, proficiency_percent, level, action, effect, outcome, employer, recency) VALUES ('semantic-versioning-1', 'Semantic Versioning', 'Cloud & DevOps', 'Implemented semantic versioning (v1.2.0, v2.1.3) across 6 microservices with automated Git tagging', 3, 15, 'Advanced', 'Established semver conventions with Git tags', 'Clear version history and dependency tracking', 'Transparent release management', 'Portfolio', 'Current (2023-2025)');

-- Architecture Patterns
INSERT INTO technology (stable_id, name, category, experience, experience_years, proficiency_percent, level, action, effect, outcome, employer, recency) VALUES ('event-driven-architecture-1', 'Event-Driven Architecture', 'Architecture & Design', 'Architected event-driven systems using DynamoDB Streams, SQS, and Lambda with fire-and-forget patterns', 5, 25, 'Advanced', 'Designed async event pipelines', 'Decoupled services for independent scaling', '12ms P99 latency with 90% cost reduction', 'Portfolio', 'Current (2023-2025)');

-- serverless-architecture-1 already exists, using -2
INSERT INTO technology (stable_id, name, category, experience, experience_years, proficiency_percent, level, action, effect, outcome, employer, recency) VALUES ('serverless-architecture-2', 'Serverless (Multi-Cloud)', 'Architecture & Design', 'Built serverless systems across Cloudflare Workers, AWS Lambda, and GCP Cloud Functions, achieving £0 operational cost', 5, 25, 'Advanced', 'Architected pure serverless platform', 'Eliminated infrastructure management', '3,000 queries/month at £0 cost', 'Portfolio', 'Current (2023-2025)');

INSERT INTO technology (stable_id, name, category, experience, experience_years, proficiency_percent, level, action, effect, outcome, employer, recency) VALUES ('hmac-security-1', 'HMAC Security', 'Architecture & Design', 'Implemented HMAC-SHA256 signing and validation for cross-cloud webhooks (AWS → GCP)', 3, 15, 'Advanced', 'Designed HMAC webhook authentication', 'Secured cross-cloud data pipelines', 'Verified message integrity across providers', 'Portfolio', 'Current (2023-2025)');

INSERT INTO technology (stable_id, name, category, experience, experience_years, proficiency_percent, level, action, effect, outcome, employer, recency) VALUES ('real-time-systems-1', 'Real-Time Systems', 'Architecture & Design', 'Architected real-time dashboard using Firestore WebSocket listeners for instant updates', 3, 15, 'Advanced', 'Implemented Firestore onSnapshot() pattern', 'Eliminated polling overhead', 'Sub-second UI synchronization', 'Portfolio', 'Current (2023-2025)');

INSERT INTO technology (stable_id, name, category, experience, experience_years, proficiency_percent, level, action, effect, outcome, employer, recency) VALUES ('fire-and-forget-1', 'Fire-and-Forget Pattern', 'Architecture & Design', 'Implemented fire-and-forget writes to DynamoDB with async processing via Streams and SQS', 3, 15, 'Advanced', 'Decoupled write path from processing', 'Non-blocking writes with async pipeline', '12ms write latency with reliable processing', 'Portfolio', 'Current (2023-2025)');

INSERT INTO technology (stable_id, name, category, experience, experience_years, proficiency_percent, level, action, effect, outcome, employer, recency) VALUES ('multi-cloud-architecture-1', 'Multi-Cloud Architecture', 'Architecture & Design', 'Designed 6 microservices across Cloudflare, AWS, and GCP, achieving 87.5% architectural purity', 3, 15, 'Expert', 'Architected cross-cloud service mesh', 'Optimal service placement per cloud strengths', '£0 operational cost with 12ms latency', 'Portfolio', 'Current (2023-2025)');

INSERT INTO technology (stable_id, name, category, experience, experience_years, proficiency_percent, level, action, effect, outcome, employer, recency) VALUES ('cost-optimization-1', 'Cost Optimization', 'Architecture & Design', 'Achieved £0 operational cost through strategic free-tier exploitation and 10:1 batching optimization', 10, 50, 'Expert', 'Designed constraint-driven architecture', 'Maximized free tier utilization', '3,000 queries/month at £0 cost', 'Portfolio', 'Current (2023-2025)');
